# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-03 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='student_id',
            new_name='faculty_id',
        ),
    ]
