# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-03 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180704_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='username',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
