# Generated by Django 2.0.3 on 2018-08-20 17:01

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180815_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2018, 8, 20)),
        ),
    ]
