# Generated by Django 2.0.3 on 2018-08-03 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20180803_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='password',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='username',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='first_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
